server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:BD_leon_dalia_T1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT
jwt.secret=ClaveSuperSegura256bitsLeonDalia2026
jwt.expiration=86400000

# CORS
cors.allowed.origins=http://localhost:3000

